/**
 * Electron API 封装层
 * 统一管理 IPC 调用，提供语义化接口
 */

import { writeTextToClipboard } from '../utils/clipboardWriter.js'

const isElectron = typeof window !== 'undefined' && !!window.electronAPI

// Vue/Pinia expose nested state as Proxy objects. Electron's context bridge
// cannot clone those values, so every crafting payload must cross the bridge
// as plain data instead of leaking renderer reactivity into IPC.
const craftingIpcPayload = (value) => {
  if (value === null || typeof value !== 'object') return value
  return JSON.parse(JSON.stringify(value))
}

const mockApi = {
  emergencyStopAll: () => Promise.resolve({ success: true, stopped: [], failed: [] }),
  system: {
    detectGameDpi: () => Promise.resolve({ found: false, primaryScaleFactor: 1, error: '非 Electron 环境' }),
    updateGameWindowTitles: (titles) => Promise.resolve({ success: true, titles }),
    updateGameWindowProcessNames: (processNames) => Promise.resolve({ success: true, processNames }),
    getStartupHealth: () => Promise.resolve({ checkedAt: new Date().toISOString(), items: [] }),
    getDiagnostics: () => Promise.resolve(null),
    exportDiagnostics: () => Promise.resolve({ success: false, canceled: true }),
    recordDiagnosticEvent: () => Promise.resolve({ recorded: false }),
    startDiagnosticCapture: () => Promise.resolve({ success: false }),
    getDiagnosticCaptureStatus: () => Promise.resolve({ success: true, activeCapture: null, lastCapture: null }),
    finishDiagnosticCapture: () => Promise.resolve({ success: false }),
    cancelDiagnosticCapture: () => Promise.resolve({ success: true }),
  },
  feedback: {
    pickAttachments: () => Promise.resolve({ success: false, canceled: false, attachments: [], error: '仅 Electron 客户端支持问题反馈', errorCode: 'FEEDBACK_SERVICE_UNAVAILABLE' }),
    submit: () => Promise.resolve({ success: false, error: '仅 Electron 客户端支持问题反馈', errorCode: 'FEEDBACK_SERVICE_UNAVAILABLE' }),
    onProgress: () => () => {}
  },
  update: {
    getState: () => Promise.resolve({ mode: 'manual', source: 'cnb', currentVersion: '', status: 'idle', supported: false, progress: null, error: '' }),
    configure: (input) => Promise.resolve({ mode: input?.mode === 'automatic' ? 'automatic' : 'manual', source: input?.source === 'github' ? 'github' : 'cnb', currentVersion: '', status: 'idle', supported: false, progress: null, error: '' }),
    check: () => Promise.resolve({ success: false }),
    download: () => Promise.resolve({ success: false }),
    restartAndInstall: () => Promise.resolve({ success: false }),
    onStateChanged: () => () => {}
  },
  script: {
    executePython: () => Promise.reject(new Error('非 Electron 环境')),
    generateAndExecute: () => Promise.reject(new Error('非 Electron 环境')),
    restartLastItem: () => Promise.resolve({ success: false, error: '非 Electron 环境' }),
    stop: () => Promise.resolve({ success: true }),
    getStatus: () => Promise.resolve({ isRunning: false }),
    onStatusChanged: () => () => {},
    detectPythonPath: () => Promise.resolve(null),
  },
  file: {
    save: () => Promise.resolve(true),
    read: () => Promise.resolve(''),
    getPaths: () => Promise.resolve({}),
    watcher: {
      start: () => Promise.resolve(true),
      stop: () => Promise.resolve(true),
    }
  },
  clipboard: {
    writeText: (text) => writeTextToClipboard(text),
  },
  shortcut: {
    initFromSettings: () => Promise.resolve({ success: true, failed: [] }),
    register: () => Promise.resolve({ success: true }),
    unregister: () => Promise.resolve({ success: true }),
    beginCapture: () => Promise.resolve({ success: true }),
    endCapture: () => Promise.resolve({ success: true, failed: [] }),
    setScopeEnabled: (enabled) => Promise.resolve({ success: true, enabled: Boolean(enabled), available: true, gameForeground: false }),
    getScopeState: () => Promise.resolve({ enabled: true, available: true, gameForeground: false, registered: [], intended: [] }),
    onTriggered: () => { },
    onInit: () => { },
    onScopeChanged: () => () => { },
  },
  window: {
    minimize: () => { },
    maximize: () => { },
    close: () => { },
    toggleAlwaysOnTop: () => Promise.resolve(false),
    isAlwaysOnTop: () => Promise.resolve(false),
    onMaximized: () => { },
    openDebugOverlay: () => Promise.resolve({ success: true }),
    closeDebugOverlay: () => Promise.resolve({ success: true }),
    updateDebugOverlay: () => Promise.resolve({ success: true }),
    setDevToolsVisible: (visible) => Promise.resolve({ visible: Boolean(visible) }),
    getDevToolsVisible: () => Promise.resolve({ visible: false }),
    onDevToolsVisibilityChanged: () => () => { },
    pickScreenCoordinate: () => Promise.resolve({ canceled: true }),
    getScreenPickerContext: () => Promise.resolve({ mode: 'point' }),
    submitScreenCoordinate: () => { },
    submitScreenRegion: () => { },
    cancelScreenCoordinatePicker: () => { },
    moveOverlay: () => { },
  },
  puzzle: {
    pickInventoryRegion: () => Promise.resolve({ canceled: true }),
    pickAtlasRegion: () => Promise.resolve({ canceled: true }),
    pickInventoryTabPoint: () => Promise.resolve({ canceled: true }),
    clearRegion: () => Promise.resolve({ success: true }),
    getConfiguration: () => Promise.resolve({ previews: { inventory: '', atlas: '' }, states: {} }),
    listCalibration: () => Promise.resolve([]),
    saveCalibration: () => Promise.resolve([]),
    removeCalibration: () => Promise.resolve([]),
    resetCalibration: () => Promise.resolve([]),
    analyze: () => Promise.resolve({
      success: false,
      error: { code: 'ELECTRON_REQUIRED', message: '海图识别仅支持 Electron 客户端' }
    }),
    startAutoPlacement: () => Promise.resolve({ success: false, error: { code: 'ELECTRON_REQUIRED', message: '海图自动放置仅支持 Electron 客户端' } }),
    stopAutoPlacement: () => Promise.resolve({ success: true, status: 'stopped' }),
    getAutoPlacementStatus: () => Promise.resolve({ status: 'idle' }),
    completeChart: () => Promise.resolve({ success: true }),
    probeBorderMods: () => Promise.resolve({ success: false, error: { code: 'ELECTRON_REQUIRED', message: '边缘词缀识别仅支持 Electron 客户端' } }),
    onAnalysisUpdated: () => () => {},
    onAutoPlacementUpdated: () => () => {}
  },
  events: {
    onPythonOutput: () => { },
    onUpdateOverlay: () => { },
    onUpdateOverlaySettings: () => { },
    onScriptStopped: () => { },
    onBagDetectionMatch: () => () => { },
    onBagStashProgress: () => () => { },
    onBagStashCompleted: () => () => { },
    onBagStashStopped: () => () => { },
    onBagDetectionStopped: () => () => { },
    onUpdateDebugOverlay: () => { },
  },
  overlay: {
    updateSettings: () => Promise.resolve({ success: true }),
    selectBackground: () => Promise.resolve({ success: false, canceled: true }),
    importBackground: () => Promise.resolve({ success: false, error: { code: 'ELECTRON_REQUIRED', message: '背景导入仅支持 Electron 客户端' } }),
    getPathForFile: () => '',
  },
  bag: {
    startDetection: () => Promise.reject(new Error('非 Electron 环境')),
    stopDetection: () => Promise.resolve({ success: true }),
    startStash: () => Promise.reject(new Error('非 Electron 环境')),
    stopStash: () => Promise.resolve({ success: true }),
    updateOperationDelay: () => Promise.resolve({ success: true }),
    updateEmptySlotThreshold: (emptySlotThreshold) => Promise.resolve({ success: true, emptySlotThreshold }),
    updatePreferences: () => Promise.resolve({ success: true }),
    updateRuntimeConfig: (config) => Promise.resolve({ success: true, config, revision: 1 }),
    uploadTemplate: () => Promise.reject(new Error('非 Electron 环境')),
    captureTemplate: () => Promise.reject(new Error('非 Electron 环境')),
    getOverlayState: () => Promise.resolve(null),
    onOverlayState: () => () => {},
    moveOverlay: () => {},
    updateInterfaceConfig: () => Promise.resolve({ success: true }),
  },
  automationTiming: {
    update: () => Promise.resolve({ success: false, error: '非 Electron 环境' })
  },
  poeCnAccount: {
    getStatus: () => Promise.resolve({ success: true, data: { authenticated: false, mode: null, accountName: '' } }),
    restore: () => Promise.resolve({ success: true, data: { authenticated: false, mode: null, accountName: '' } }),
    openWebLogin: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持网页登录' } }),
    completeWebLogin: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持网页登录' } }),
    setSessionToken: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持会话认证' } }),
    logout: () => Promise.resolve({ success: true, data: { authenticated: false, mode: null, accountName: '' } }),
    listLeagues: () => Promise.resolve({ success: true, data: [] }),
    setLeague: (league) => Promise.resolve({ success: true, data: { league: String(league || '') } }),
    onStatusChanged: () => () => {}
  },
  chaosRecipe: {
    listTabs: () => Promise.resolve({ success: true, data: [] }),
    refresh: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持仓库读取' } }),
    getSnapshot: () => Promise.resolve({ success: false, error: { message: '暂无仓库快照' } }),
    pickGridRegion: () => Promise.resolve({ success: true, data: { canceled: true } }),
    openOverlay: () => Promise.resolve({ success: true, data: null }),
    closeOverlay: () => Promise.resolve({ success: true }),
    getOverlayState: () => Promise.resolve({ success: true, data: null }),
    startAutomation: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持自动取件' } }),
    pauseAutomation: () => Promise.resolve({ success: false }),
    resumeAutomation: () => Promise.resolve({ success: false }),
    stopAutomation: () => Promise.resolve({ success: true }),
    getAutomationStatus: () => Promise.resolve({ success: true, data: { status: 'idle' } }),
    updateRuntime: () => Promise.resolve({ success: true, data: { enabled: false } }),
    getControlState: () => Promise.resolve({ success: true, data: { visible: false } }),
    controlRefresh: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持仓库读取' } }),
    selectControlRecipe: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持配方切换' } }),
    controlPreview: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持高亮' } }),
    controlAction: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持自动取件' } }),
    moveControl: () => {},
    resizeControl: () => {},
    getDetectionState: () => Promise.resolve({ success: true, data: {} }),
    updateDetectionConfig: () => Promise.resolve({ success: true, data: {} }),
    onAutomationEvent: () => () => {},
    onOverlayState: () => () => {},
    onControlState: () => () => {},
    onControlOffset: () => () => {},
    onSnapshotUpdated: () => () => {},
    onControlRecipeSelected: () => () => {}
  },
  stashPickup: {
    updateRuntime: () => Promise.resolve({ success: true, data: { status: 'idle' } }),
    preview: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持检测预览' } }),
    start: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持自动取件' } }),
    stop: () => Promise.resolve({ success: true, data: { status: 'stopped' } }),
    getStatus: () => Promise.resolve({ success: true, data: { status: 'idle' } }),
    pickGridRegion: () => Promise.resolve({ success: true, data: { canceled: true } }),
    onEvent: () => () => {}
  },
  junfeng: {
    updateRuntime: () => Promise.resolve({ success: true, data: { status: 'idle' } }),
    preview: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持君锋镇预览' } }),
    start: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持君锋镇取件' } }),
    stop: () => Promise.resolve({ success: true, data: { status: 'stopped' } }),
    getStatus: () => Promise.resolve({ success: true, data: { status: 'idle' } }),
    pickGridRegion: () => Promise.resolve({ success: true, data: { canceled: true } }),
    listCorrections: () => Promise.resolve({ success: true, data: [] }),
    addCorrection: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持校准' } }),
    removeCorrection: () => Promise.resolve({ success: true, data: false }),
    resetCorrections: () => Promise.resolve({ success: true, data: [] }),
    rebuildCorrections: () => Promise.resolve({ success: true, data: [] }),
    pickTrainingRegion: () => Promise.resolve({ success: true, data: { canceled: true } }),
    previewTraining: () => Promise.resolve({ success: false, error: { message: '仅 Electron 开发版支持训练采集' } }),
    saveTrainingSession: () => Promise.resolve({ success: false, error: { message: '仅 Electron 开发版支持训练采集' } }),
    listTrainingSessions: () => Promise.resolve({ success: true, data: [] }),
    getTrainingSession: () => Promise.resolve({ success: false, error: { message: '仅 Electron 开发版支持训练会话复核' } }),
    updateTrainingSession: () => Promise.resolve({ success: false, error: { message: '仅 Electron 开发版支持训练会话修改' } }),
    deleteTrainingSession: () => Promise.resolve({ success: false, error: { message: '仅 Electron 开发版支持训练会话删除' } }),
    getTrainingStatus: () => Promise.resolve({ success: true, data: { status: 'idle', available: false } }),
    trainModel: () => Promise.resolve({ success: false, error: { message: '仅 Electron 开发版支持模型训练' } }),
    evaluateModel: () => Promise.resolve({ success: false, error: { message: '仅 Electron 开发版支持模型最终测试' } }),
    onTrainingEvent: () => () => {},
    onEvent: () => () => {}
  },
  highlightCalibration: {
    list: () => Promise.resolve({ success: true, data: [] }),
    save: () => Promise.resolve({ success: false, error: { message: '仅 Electron 客户端支持校准' } }),
    remove: () => Promise.resolve({ success: true, data: false }),
    reset: () => Promise.resolve({ success: true, data: [] })
  },
  stashTabs: {
    pickRootRegion: () => Promise.resolve({ success: true, canceled: true }),
    preview: () => Promise.resolve({ success: false, error: '仅 Electron 客户端支持仓库页识别' })
  },
  priceCheck: {
    getStatus: () => Promise.resolve({ success: true, data: { auth: { authenticated: false }, catalog: null } }),
    updateRuntime: (runtime) => Promise.resolve({ success: true, data: { enabled: Boolean(runtime?.enabled) } }),
    capture: () => Promise.reject(new Error('仅 Electron 客户端支持国服查价')),
    rerun: () => Promise.reject(new Error('仅 Electron 客户端支持国服查价')),
    retryCatalog: () => Promise.reject(new Error('仅 Electron 客户端支持刷新国服交易目录')),
    loadMore: () => Promise.reject(new Error('仅 Electron 客户端支持国服查价')),
    resolveStatCandidate: () => Promise.reject(new Error('仅 Electron 客户端支持国服查价')),
    getOverlayState: () => Promise.resolve({ success: true, data: null }),
    closeOverlay: () => Promise.resolve({ success: true }),
    openOfficial: () => Promise.reject(new Error('仅 Electron 客户端支持国服查价')),
    onOverlayState: () => () => {}
  },
  combat: {
    startPotion: () => Promise.reject(new Error('非 Electron 环境')),
    stopPotion: () => Promise.resolve({ success: true }),
    getPotionStatus: () => Promise.resolve({ running: false, processId: null }),
    updatePotionConfig: (config) => Promise.resolve({ success: true, config, revision: 1, running: false }),
    startLoop: () => Promise.reject(new Error('非 Electron 环境')),
    stopLoop: () => Promise.resolve({ success: true }),
    getLoopStatus: () => Promise.resolve({ running: false, processId: null }),
    updateLoopConfig: (config) => Promise.resolve({ success: true, config, revision: 1, running: false }),
    samplePixel: () => Promise.reject(new Error('非 Electron 环境')),
    executePortal: () => Promise.reject(new Error('非 Electron 环境')),
    onStatus: () => () => {}
  },
  storyOverlay: {
    open: () => Promise.resolve({ success: true }),
    close: () => Promise.resolve({ success: true }),
    update: () => Promise.resolve({ success: true }),
    getState: () => Promise.resolve(null),
    resize: () => Promise.resolve({ success: true }),
    setOpacity: () => Promise.resolve({ success: true }),
    updateLayout: () => Promise.resolve({ success: true }),
    move: () => {},
    onState: () => () => {},
    onDividerRatio: () => () => {}
  },
  crafting: {
    getStatus: () => Promise.resolve({ source: 'builtin', manifest: null }),
    listCategories: () => Promise.resolve([]),
    searchBases: () => Promise.resolve({ items: [], total: 0 }),
    searchModifiers: () => Promise.resolve({ items: [], total: 0 }),
    searchModifierCatalog: () => Promise.resolve({ groups: [], sourceCoverage: {}, totalFamilies: 0 }),
    searchAffixSuggestions: () => Promise.resolve({ items: [], total: 0 }),
    searchEldritchImplicitSuggestions: () => Promise.resolve({ items: [], total: 0 }),
    createManualSession: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    applyManualCurrency: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    listManualEssences: () => Promise.resolve({ items: [], unresolvedCount: 0 }),
    applyManualEssence: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    listManualBenchCrafts: () => Promise.resolve({ items: [], unresolvedCount: 0 }),
    applyManualBenchCraft: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    listManualFossils: () => Promise.resolve({ items: [], resonators: [], supportedCount: 0 }),
    applyManualFossils: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    listManualHarvestCrafts: () => Promise.resolve({ items: [], categories: [], total: 0, executableCount: 0 }),
    applyManualHarvestCraft: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    listManualEldritchCrafts: () => Promise.resolve({ items: [], total: 0, executableCount: 0, dominance: { source: null, affixType: null, label: '无支配' } }),
    applyManualEldritchCraft: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    listManualInfluenceCrafts: () => Promise.resolve({ items: [], total: 0, executableCount: 0, donor: null, influenceLabels: {} }),
    listAwakenerDonorCandidates: () => Promise.resolve({ bases: [], influences: [], candidates: [] }),
    configureAwakenerDonor: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    clearAwakenerDonor: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    applyManualInfluenceCraft: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    listManualVeiledCrafts: () => Promise.resolve({ items: [], total: 0, executableCount: 0, pending: null, options: [], canUnveil: false, unveilUnavailableReason: '' }),
    applyManualVeiledCraft: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    selectManualVeiledOption: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    listManualBeastcrafts: () => Promise.resolve({ items: [], total: 0, executableCount: 0, beastLevel: 83, pendingSplitResults: [], imprint: null, foreseeing: false }),
    applyManualBeastcraft: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    selectManualSplitResult: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    previewManualCurrency: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    undoManualAction: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    redoManualAction: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    resetManualSession: () => Promise.reject(new Error('仅 Electron 客户端支持模拟功能')),
    updateData: () => Promise.reject(new Error('仅 Electron 客户端支持数据更新')),
    cancelUpdate: () => Promise.resolve({ success: true }),
    getPrices: () => Promise.resolve({ records: [], overrides: {}, health: 'unavailable' }),
    refreshPrices: () => Promise.reject(new Error('仅 Electron 客户端支持价格更新')),
    setPriceOverride: () => Promise.resolve({ success: true }),
    removePriceOverride: () => Promise.resolve({ success: true }),
    startPlan: () => Promise.reject(new Error('仅 Electron 客户端支持做装计算')),
    cancelPlan: () => Promise.resolve({ success: true }),
    onUpdateProgress: () => () => {},
    onPlanEvent: () => () => {}
  }
}

export const electronApi = isElectron ? {
  emergencyStopAll: () => window.electronAPI.emergencyStopAll?.(),
  system: {
    detectGameDpi: () => window.electronAPI.detectGameDpi?.(),
    updateGameWindowTitles: (titles) => window.electronAPI.updateGameWindowTitles?.(craftingIpcPayload(titles)),
    updateGameWindowProcessNames: (processNames) => window.electronAPI.updateGameWindowProcessNames?.(craftingIpcPayload(processNames)),
    getStartupHealth: () => window.electronAPI.getStartupHealth?.(),
    getDiagnostics: (payload) => window.electronAPI.getDiagnostics?.(craftingIpcPayload(payload)),
    exportDiagnostics: (payload) => window.electronAPI.exportDiagnostics?.(craftingIpcPayload(payload)),
    recordDiagnosticEvent: (event) => window.electronAPI.recordDiagnosticEvent?.(craftingIpcPayload(event)),
    startDiagnosticCapture: (input) => window.electronAPI.startDiagnosticCapture?.(craftingIpcPayload(input)),
    getDiagnosticCaptureStatus: () => window.electronAPI.getDiagnosticCaptureStatus?.(),
    finishDiagnosticCapture: (input) => window.electronAPI.finishDiagnosticCapture?.(craftingIpcPayload(input)),
    cancelDiagnosticCapture: (input) => window.electronAPI.cancelDiagnosticCapture?.(craftingIpcPayload(input)),
  },
  feedback: {
    pickAttachments: () => window.electronAPI.pickFeedbackAttachments?.(),
    submit: (input) => window.electronAPI.submitFeedback?.(craftingIpcPayload(input)),
    onProgress: (callback) => window.electronAPI.onFeedbackProgress?.(callback) || (() => {})
  },
  update: {
    getState: () => window.electronAPI.getApplicationUpdateState?.(),
    configure: (input) => window.electronAPI.configureApplicationUpdate?.(craftingIpcPayload(input)),
    check: () => window.electronAPI.checkApplicationUpdate?.(),
    download: () => window.electronAPI.downloadApplicationUpdate?.(),
    restartAndInstall: () => window.electronAPI.restartAndInstallApplicationUpdate?.(),
    onStateChanged: (callback) => window.electronAPI.onApplicationUpdateStateChanged?.(callback) || (() => {})
  },
  script: {
    executePython: (path, args) => window.electronAPI.executePython(path, args),
    generateAndExecute: (config) => window.electronAPI.generateAndExecuteScript(config),
    restartLastItem: () => window.electronAPI.restartLastItemScript?.(),
    stop: () => window.electronAPI.stopScript(),
    getStatus: () => window.electronAPI.getScriptStatus(),
    onStatusChanged: (callback) => window.electronAPI.onScriptStatusChanged?.(callback) || (() => {}),
    detectPythonPath: () => window.electronAPI.detectPythonPath(),
  },

  file: {
    save: (path, content) => window.electronAPI.saveFile(path, content),
    read: (path) => window.electronAPI.readFile(path),
    getPaths: () => window.electronAPI.getFilePaths(),
    watcher: {
      start: (config) => window.electronAPI.startFileWatcher(config),
      stop: () => window.electronAPI.stopFileWatcher(),
    }
  },

  clipboard: {
    writeText: (text) => writeTextToClipboard(text, {
      electronWrite: window.electronAPI.writeClipboardText
    }),
  },

  shortcut: {
    initFromSettings: (shortcuts) => window.electronAPI.initShortcutsFromSettings(shortcuts),
    register: (accelerator, callback) => window.electronAPI.registerGlobalShortcut(accelerator, callback),
    unregister: (accelerator) => window.electronAPI.unregisterGlobalShortcut(accelerator),
    beginCapture: () => window.electronAPI.beginShortcutCapture?.(),
    endCapture: () => window.electronAPI.endShortcutCapture?.(),
    setScopeEnabled: (enabled) => window.electronAPI.setShortcutScopeEnabled?.(Boolean(enabled)),
    getScopeState: () => window.electronAPI.getShortcutScopeState?.(),
    onTriggered: (callback) => window.electronAPI.onShortcutTriggered(callback),
    onInit: (callback) => window.electronAPI.onInitShortcuts(callback),
    onScopeChanged: (callback) => window.electronAPI.onShortcutScopeChanged?.(callback) || (() => {}),
  },

  window: {
    minimize: () => window.electronAPI.minimizeWindow(),
    maximize: () => window.electronAPI.maximizeWindow(),
    close: () => window.electronAPI.closeWindow(),
    closeOverlay: () => window.electronAPI.closeOverlayWindow(),
    toggleAlwaysOnTop: () => window.electronAPI.toggleAlwaysOnTop(),
    isAlwaysOnTop: () => window.electronAPI.isAlwaysOnTop(),
    onMaximized: (callback) => window.electronAPI.onWindowMaximized(callback),
    move: (x, y) => window.electronAPI.moveWindow(x, y),
    openDebugOverlay: () => window.electronAPI.openDebugOverlay?.(),
    closeDebugOverlay: () => window.electronAPI.closeDebugOverlay?.(),
    updateDebugOverlay: (data) => window.electronAPI.updateDebugOverlay?.(data),
    setDevToolsVisible: (visible) => window.electronAPI.setDevToolsVisible?.(visible),
    getDevToolsVisible: () => window.electronAPI.getDevToolsVisible?.(),
    onDevToolsVisibilityChanged: (callback) => window.electronAPI.onDevToolsVisibilityChanged?.(callback),
    pickScreenCoordinate: () => window.electronAPI.pickScreenCoordinate?.(),
    getScreenPickerContext: () => window.electronAPI.getScreenPickerContext?.(),
    submitScreenCoordinate: (point) => window.electronAPI.submitScreenCoordinate?.(point),
    submitScreenRegion: (rectangle) => window.electronAPI.submitScreenRegion?.(rectangle),
    cancelScreenCoordinatePicker: () => window.electronAPI.cancelScreenCoordinatePicker?.(),
    moveOverlay: (drag) => window.electronAPI.moveCraftingOverlay?.(craftingIpcPayload(drag))
  },
  puzzle: {
    pickInventoryRegion: () => window.electronAPI.pickPuzzleInventoryRegion?.(),
    pickAtlasRegion: () => window.electronAPI.pickPuzzleAtlasRegion?.(),
    pickInventoryTabPoint: (page) => window.electronAPI.pickPuzzleInventoryTabPoint?.(page),
    clearRegion: (type) => window.electronAPI.clearPuzzleRegion?.(type),
    getConfiguration: (request) => window.electronAPI.getPuzzleConfiguration?.(craftingIpcPayload(request)),
    listCalibration: () => window.electronAPI.listPuzzleCalibration?.(),
    saveCalibration: (items) => window.electronAPI.savePuzzleCalibration?.(craftingIpcPayload(items)),
    removeCalibration: (id) => window.electronAPI.removePuzzleCalibration?.(id),
    resetCalibration: () => window.electronAPI.resetPuzzleCalibration?.(),
    analyze: (request) => window.electronAPI.analyzePuzzle?.(craftingIpcPayload(request)),
    startAutoPlacement: (request) => window.electronAPI.startPuzzleAutoPlacement?.(craftingIpcPayload(request)),
    stopAutoPlacement: (reason) => window.electronAPI.stopPuzzleAutoPlacement?.(reason),
    getAutoPlacementStatus: () => window.electronAPI.getPuzzleAutoPlacementStatus?.(),
    completeChart: () => window.electronAPI.completePuzzleChart?.(),
    probeBorderMods: (request) => window.electronAPI.probePuzzleBorderMods?.(craftingIpcPayload(request)),
    onAnalysisUpdated: (callback) => window.electronAPI.onPuzzleAnalysisUpdated?.(callback) || (() => {}),
    onAutoPlacementUpdated: (callback) => window.electronAPI.onPuzzleAutoPlacementUpdated?.(callback) || (() => {})
  },
  setIgnoreMouseEvents: (ignore, options) => window.electronAPI.setIgnoreMouseEvents(ignore, options),

  events: {
    onPythonOutput: (callback) => window.electronAPI.onPythonScriptOutput(callback),
    onUpdateOverlay: (callback) => window.electronAPI.onUpdateOverlay(callback),
    onUpdateOverlaySettings: (callback) => window.electronAPI.onUpdateOverlaySettings(callback),
    onScriptStopped: (callback) => window.electronAPI.onScriptStopped(callback),
    onBagDetectionMatch: (callback) => window.electronAPI.onBagDetectionMatch?.(callback),
    onBagStashProgress: (callback) => window.electronAPI.onBagStashProgress?.(callback),
    onBagStashCompleted: (callback) => window.electronAPI.onBagStashCompleted?.(callback),
    onBagStashStopped: (callback) => window.electronAPI.onBagStashStopped?.(callback),
    onBagDetectionStopped: (callback) => window.electronAPI.onBagDetectionStopped?.(callback),
    onUpdateDebugOverlay: (callback) => window.electronAPI.onUpdateDebugOverlay?.(callback),
  },

  overlay: {
    updateSettings: (settings) => window.electronAPI.updateOverlaySettings(settings),
    selectBackground: () => window.electronAPI.selectOverlayBackground(),
    importBackground: (sourcePath) => window.electronAPI.importOverlayBackground(sourcePath),
    getPathForFile: (file) => window.electronAPI.getPathForFile(file),
  },

  bag: {
    startDetection: (config) => window.electronAPI.startBagDetection?.(config),
    stopDetection: () => window.electronAPI.stopBagDetection?.(),
    startStash: () => window.electronAPI.startBagStash?.(),
    stopStash: () => window.electronAPI.stopBagStash?.(),
    updateOperationDelay: (operationDelayMs) => window.electronAPI.updateBagOperationDelay?.(operationDelayMs),
    updateEmptySlotThreshold: (emptySlotThreshold) => window.electronAPI.updateBagEmptySlotThreshold?.(emptySlotThreshold),
    updatePreferences: (preferences) => window.electronAPI.updateBagPreferences?.(preferences),
    updateRuntimeConfig: (config) => window.electronAPI.updateBagRuntimeConfig?.(craftingIpcPayload(config)),
    uploadTemplate: (path, type) => window.electronAPI.uploadBagTemplate?.(path, type),
    captureTemplate: (type) => window.electronAPI.captureBagTemplate?.(type),
    getOverlayState: () => window.electronAPI.getBagStashOverlayState?.(),
    onOverlayState: (callback) => window.electronAPI.onBagStashOverlayState?.(callback) || (() => {}),
    moveOverlay: (drag) => window.electronAPI.moveBagStashOverlay?.(craftingIpcPayload(drag)),
    updateInterfaceConfig: (config) => window.electronAPI.updateBagInterfaceConfig?.(craftingIpcPayload(config)),
  },
  automationTiming: {
    update: (timing) => window.electronAPI.updateAutomationTiming?.(craftingIpcPayload(timing))
  },
  poeCnAccount: {
    getStatus: () => window.electronAPI.getPoeCnAccountStatus?.(),
    restore: () => window.electronAPI.restorePoeCnAccount?.(),
    openWebLogin: () => window.electronAPI.openPoeCnAccountWebLogin?.(),
    completeWebLogin: () => window.electronAPI.completePoeCnAccountWebLogin?.(),
    setSessionToken: (token) => window.electronAPI.setPoeCnAccountSessionToken?.(String(token || '')),
    logout: () => window.electronAPI.logoutPoeCnAccount?.(),
    listLeagues: () => window.electronAPI.listPoeCnAccountLeagues?.(),
    setLeague: (league) => window.electronAPI.setPoeCnAccountLeague?.(String(league || '')),
    onStatusChanged: (callback) => window.electronAPI.onPoeCnAccountStatusChanged?.(callback) || (() => {})
  },
  chaosRecipe: {
    listTabs: (league) => window.electronAPI.listChaosRecipeTabs?.(String(league || '')),
    refresh: (request) => window.electronAPI.refreshChaosRecipe?.(craftingIpcPayload(request)),
    getSnapshot: () => window.electronAPI.getChaosRecipeSnapshot?.(),
    pickGridRegion: () => window.electronAPI.pickChaosRecipeGridRegion?.(),
    openOverlay: (request, calibration) => window.electronAPI.openChaosRecipeOverlay?.(
      craftingIpcPayload(request),
      craftingIpcPayload(calibration)
    ),
    closeOverlay: () => window.electronAPI.closeChaosRecipeOverlay?.(),
    getOverlayState: () => window.electronAPI.getChaosRecipeOverlayState?.(),
    startAutomation: (request) => window.electronAPI.startChaosRecipeAutomation?.(craftingIpcPayload(request)),
    pauseAutomation: () => window.electronAPI.pauseChaosRecipeAutomation?.(),
    resumeAutomation: () => window.electronAPI.resumeChaosRecipeAutomation?.(),
    stopAutomation: () => window.electronAPI.stopChaosRecipeAutomation?.(),
    getAutomationStatus: () => window.electronAPI.getChaosRecipeAutomationStatus?.(),
    updateRuntime: (runtime) => window.electronAPI.updateChaosRecipeRuntime?.(craftingIpcPayload(runtime)),
    getControlState: () => window.electronAPI.getChaosRecipeControlState?.(),
    controlRefresh: () => window.electronAPI.refreshChaosRecipeFromControl?.(),
    selectControlRecipe: (recipeId) => window.electronAPI.selectChaosRecipeFromControl?.(String(recipeId || '')),
    controlPreview: () => window.electronAPI.previewChaosRecipeFromControl?.(),
    controlAction: () => window.electronAPI.runChaosRecipeControlAction?.(),
    moveControl: (drag) => window.electronAPI.moveChaosRecipeControl?.(craftingIpcPayload(drag)),
    resizeControl: (size) => window.electronAPI.resizeChaosRecipeControl?.(craftingIpcPayload(size)),
    getDetectionState: () => window.electronAPI.getInterfaceDetectionState?.(),
    updateDetectionConfig: (runtime) => window.electronAPI.updateInterfaceDetectionConfig?.(craftingIpcPayload(runtime)),
    onAutomationEvent: (callback) => window.electronAPI.onChaosRecipeAutomationEvent?.(callback) || (() => {}),
    onOverlayState: (callback) => window.electronAPI.onChaosRecipeOverlayState?.(callback) || (() => {}),
    onControlState: (callback) => window.electronAPI.onChaosRecipeControlState?.(callback) || (() => {}),
    onControlOffset: (callback) => window.electronAPI.onChaosRecipeControlOffset?.(callback) || (() => {}),
    onSnapshotUpdated: (callback) => window.electronAPI.onChaosRecipeSnapshotUpdated?.(callback) || (() => {}),
    onControlRecipeSelected: (callback) => window.electronAPI.onChaosRecipeControlRecipeSelected?.(callback) || (() => {})
  },
  stashPickup: {
    updateRuntime: (runtime) => window.electronAPI.updateStashPickupRuntime?.(craftingIpcPayload(runtime)),
    preview: () => window.electronAPI.previewStashPickup?.(),
    start: () => window.electronAPI.startStashPickup?.(),
    stop: () => window.electronAPI.stopStashPickup?.(),
    getStatus: () => window.electronAPI.getStashPickupStatus?.(),
    pickGridRegion: () => window.electronAPI.pickStashPickupGridRegion?.(),
    onEvent: (callback) => window.electronAPI.onStashPickupEvent?.(callback) || (() => {})
  },
  junfeng: {
    updateRuntime: (runtime) => window.electronAPI.updateJunfengRuntime?.(craftingIpcPayload(runtime)),
    preview: () => window.electronAPI.previewJunfeng?.(),
    start: () => window.electronAPI.startJunfeng?.(),
    stop: () => window.electronAPI.stopJunfeng?.(),
    getStatus: () => window.electronAPI.getJunfengStatus?.(),
    pickGridRegion: () => window.electronAPI.pickJunfengGridRegion?.(),
    listCorrections: () => window.electronAPI.listJunfengCorrections?.(),
    addCorrection: (value) => window.electronAPI.addJunfengCorrection?.(craftingIpcPayload(value)),
    removeCorrection: (id) => window.electronAPI.removeJunfengCorrection?.(String(id || '')),
    resetCorrections: () => window.electronAPI.resetJunfengCorrections?.(),
    rebuildCorrections: () => window.electronAPI.rebuildJunfengCorrections?.(),
    pickTrainingRegion: () => window.electronAPI.pickJunfengTrainingRegion?.(),
    previewTraining: (value) => window.electronAPI.previewJunfengTraining?.(craftingIpcPayload(value)),
    saveTrainingSession: (value) => window.electronAPI.saveJunfengTrainingSession?.(craftingIpcPayload(value)),
    listTrainingSessions: () => window.electronAPI.listJunfengTrainingSessions?.(),
    getTrainingSession: (id) => window.electronAPI.getJunfengTrainingSession?.(String(id || '')),
    updateTrainingSession: (value) => window.electronAPI.updateJunfengTrainingSession?.(craftingIpcPayload(value)),
    deleteTrainingSession: (id) => window.electronAPI.deleteJunfengTrainingSession?.(String(id || '')),
    getTrainingStatus: () => window.electronAPI.getJunfengTrainingStatus?.(),
    trainModel: (value) => window.electronAPI.trainJunfengModel?.(craftingIpcPayload(value)),
    evaluateModel: () => window.electronAPI.evaluateJunfengModel?.(),
    onTrainingEvent: (callback) => window.electronAPI.onJunfengTrainingEvent?.(callback) || (() => {}),
    onEvent: (callback) => window.electronAPI.onJunfengEvent?.(callback) || (() => {})
  },
  highlightCalibration: {
    list: () => window.electronAPI.listHighlightCalibration?.(),
    save: (value) => window.electronAPI.saveHighlightCalibration?.(craftingIpcPayload(value)),
    remove: (id) => window.electronAPI.removeHighlightCalibration?.(String(id || '')),
    reset: () => window.electronAPI.resetHighlightCalibration?.()
  },
  stashTabs: {
    pickRootRegion: () => window.electronAPI.pickStashTabRootRegion?.(),
    preview: (config) => window.electronAPI.previewStashTabs?.(craftingIpcPayload(config))
  },
  priceCheck: {
    getStatus: () => window.electronAPI.getPriceCheckStatus?.(),
    updateRuntime: (runtime) => window.electronAPI.updatePriceCheckRuntime?.(craftingIpcPayload(runtime)),
    updateSettings: (patch) => window.electronAPI.updatePriceCheckSettings?.(craftingIpcPayload(patch)),
    capture: (request) => window.electronAPI.capturePriceCheckItem?.(craftingIpcPayload(request)),
    rerun: (request) => window.electronAPI.rerunPriceCheck?.(craftingIpcPayload(request)),
    retryCatalog: () => window.electronAPI.retryPriceCheckCatalog?.(),
    loadMore: () => window.electronAPI.loadMorePriceCheck?.(),
    loadDistribution: () => window.electronAPI.loadPriceCheckDistribution?.(),
    resolveIdentity: (candidateKey) => window.electronAPI.resolvePriceCheckIdentity?.(String(candidateKey || '')),
    resolveStatCandidate: (unknownKey, candidateId) => window.electronAPI.resolvePriceCheckStatCandidate?.(String(unknownKey || ''), String(candidateId || '')),
    getOverlayState: () => window.electronAPI.getPriceCheckOverlayState?.(),
    closeOverlay: () => window.electronAPI.closePriceCheckOverlay?.(),
    openOfficial: () => window.electronAPI.openPriceCheckOfficial?.(),
    onOverlayState: (callback) => window.electronAPI.onPriceCheckOverlayState?.(callback) || (() => {}),
    onSettingsChanged: (callback) => window.electronAPI.onPriceCheckSettingsChanged?.(callback) || (() => {}),
    onCatalogUpdated: (callback) => window.electronAPI.onPriceCheckCatalogUpdated?.(callback) || (() => {})
  },

  combat: {
    startPotion: (payload) => window.electronAPI.startPotionAssist?.(craftingIpcPayload(payload)),
    stopPotion: () => window.electronAPI.stopPotionAssist?.(),
    getPotionStatus: () => window.electronAPI.getPotionAssistStatus?.(),
    updatePotionConfig: (config) => window.electronAPI.updatePotionAssistConfig?.(craftingIpcPayload(config)),
    startLoop: (payload) => window.electronAPI.startLoopAssist?.(craftingIpcPayload(payload)),
    stopLoop: () => window.electronAPI.stopLoopAssist?.(),
    getLoopStatus: () => window.electronAPI.getLoopAssistStatus?.(),
    updateLoopConfig: (config) => window.electronAPI.updateLoopAssistConfig?.(craftingIpcPayload(config)),
    samplePixel: (payload) => window.electronAPI.sampleCombatPixel?.(payload),
    executePortal: (payload) => window.electronAPI.executePortalAssist?.(craftingIpcPayload(payload)),
    onStatus: (callback) => window.electronAPI.onCombatStatus?.(callback) || (() => {})
  },

  storyOverlay: {
    open: (snapshot, options) => window.electronAPI.openStoryOverlay?.(snapshot, options),
    close: () => window.electronAPI.closeStoryOverlay?.(),
    update: (snapshot) => window.electronAPI.updateStoryOverlay?.(snapshot),
    getState: () => window.electronAPI.getStoryOverlayState?.(),
    resize: (size) => window.electronAPI.resizeStoryOverlay?.(size),
    setOpacity: (opacity) => window.electronAPI.setStoryOverlayOpacity?.(opacity),
    updateLayout: (layout) => window.electronAPI.updateStoryOverlayLayout?.(layout),
    move: (drag) => window.electronAPI.moveStoryOverlay?.(craftingIpcPayload(drag)),
    onState: (callback) => window.electronAPI.onStoryOverlayState?.(callback) || (() => {}),
    onDividerRatio: (callback) => window.electronAPI.onStoryOverlayDividerRatio?.(callback) || (() => {})
  },

  crafting: {
    getStatus: () => window.electronAPI.getCraftingStatus?.(),
    listCategories: () => window.electronAPI.listCraftingCategories?.(),
    searchBases: (input) => window.electronAPI.searchCraftingBases?.(craftingIpcPayload(input)),
    searchModifiers: (input) => window.electronAPI.searchCraftingModifiers?.(craftingIpcPayload(input)),
    searchModifierCatalog: (input) => window.electronAPI.searchCraftingModifierCatalog?.(craftingIpcPayload(input)),
    searchAffixSuggestions: (input) => window.electronAPI.searchCraftingAffixSuggestions?.(craftingIpcPayload(input)),
    searchEldritchImplicitSuggestions: (input) => window.electronAPI.searchCraftingEldritchImplicitSuggestions?.(craftingIpcPayload(input)),
    createManualSession: (input) => window.electronAPI.createManualCraftingSession?.(craftingIpcPayload(input)),
    applyManualCurrency: (session, actionId) => window.electronAPI.applyManualCraftingCurrency?.(craftingIpcPayload(session), actionId),
    listManualEssences: (session) => window.electronAPI.listManualCraftingEssences?.(craftingIpcPayload(session)),
    applyManualEssence: (session, essenceId) => window.electronAPI.applyManualCraftingEssence?.(craftingIpcPayload(session), essenceId),
    listManualBenchCrafts: (session) => window.electronAPI.listManualCraftingBenchCrafts?.(craftingIpcPayload(session)),
    applyManualBenchCraft: (session, benchCraftId) => window.electronAPI.applyManualCraftingBenchCraft?.(craftingIpcPayload(session), benchCraftId),
    listManualFossils: (session) => window.electronAPI.listManualCraftingFossils?.(craftingIpcPayload(session)),
    applyManualFossils: (session, input) => window.electronAPI.applyManualCraftingFossils?.(craftingIpcPayload(session), craftingIpcPayload(input)),
    listManualHarvestCrafts: (session) => window.electronAPI.listManualCraftingHarvestCrafts?.(craftingIpcPayload(session)),
    applyManualHarvestCraft: (session, craftId) => window.electronAPI.applyManualCraftingHarvestCraft?.(craftingIpcPayload(session), craftId),
    listManualEldritchCrafts: (session) => window.electronAPI.listManualCraftingEldritchCrafts?.(craftingIpcPayload(session)),
    applyManualEldritchCraft: (session, actionId) => window.electronAPI.applyManualCraftingEldritchCraft?.(craftingIpcPayload(session), actionId),
    listManualInfluenceCrafts: (session) => window.electronAPI.listManualCraftingInfluenceCrafts?.(craftingIpcPayload(session)),
    listAwakenerDonorCandidates: (session, input) => window.electronAPI.listAwakenerDonorCandidates?.(craftingIpcPayload(session), craftingIpcPayload(input)),
    configureAwakenerDonor: (session, input) => window.electronAPI.configureAwakenerDonor?.(craftingIpcPayload(session), craftingIpcPayload(input)),
    clearAwakenerDonor: (session) => window.electronAPI.clearAwakenerDonor?.(craftingIpcPayload(session)),
    applyManualInfluenceCraft: (session, actionId) => window.electronAPI.applyManualCraftingInfluenceCraft?.(craftingIpcPayload(session), actionId),
    listManualVeiledCrafts: (session) => window.electronAPI.listManualCraftingVeiledCrafts?.(craftingIpcPayload(session)),
    applyManualVeiledCraft: (session, actionId) => window.electronAPI.applyManualCraftingVeiledCraft?.(craftingIpcPayload(session), actionId),
    selectManualVeiledOption: (session, modifierId, tierId) => window.electronAPI.selectManualCraftingVeiledOption?.(craftingIpcPayload(session), modifierId, tierId),
    listManualBeastcrafts: (session, input) => window.electronAPI.listManualCraftingBeastcrafts?.(craftingIpcPayload(session), craftingIpcPayload(input)),
    applyManualBeastcraft: (session, recipeId, input) => window.electronAPI.applyManualCraftingBeastcraft?.(craftingIpcPayload(session), recipeId, craftingIpcPayload(input)),
    selectManualSplitResult: (session, itemId) => window.electronAPI.selectManualCraftingSplitResult?.(craftingIpcPayload(session), itemId),
    previewManualCurrency: (session, actionId) => window.electronAPI.previewManualCraftingCurrency?.(craftingIpcPayload(session), actionId),
    undoManualAction: (session) => window.electronAPI.undoManualCraftingAction?.(craftingIpcPayload(session)),
    redoManualAction: (session) => window.electronAPI.redoManualCraftingAction?.(craftingIpcPayload(session)),
    resetManualSession: (session) => window.electronAPI.resetManualCraftingSession?.(craftingIpcPayload(session)),
    updateData: () => window.electronAPI.updateCraftingData?.(),
    cancelUpdate: () => window.electronAPI.cancelCraftingUpdate?.(),
    getPrices: () => window.electronAPI.getCraftingPrices?.(),
    refreshPrices: (force = false) => window.electronAPI.refreshCraftingPrices?.(force),
    setPriceOverride: (resourceId, value) => window.electronAPI.setCraftingPriceOverride?.(resourceId, value),
    removePriceOverride: (resourceId) => window.electronAPI.removeCraftingPriceOverride?.(resourceId),
    startPlan: (request, options) => window.electronAPI.startCraftingPlan?.(request, options),
    cancelPlan: (taskId) => window.electronAPI.cancelCraftingPlan?.(taskId),
    onUpdateProgress: (callback) => window.electronAPI.onCraftingUpdateProgress?.(callback) || (() => {}),
    onPlanEvent: (callback) => window.electronAPI.onCraftingPlanEvent?.(callback) || (() => {})
  }
} : mockApi
