const AREA_CATALOG_VERSION = 1

const AREAS = Object.freeze({
  '2_11_endgame_town': { name: '卡鲁海滩', type: 'town' },
  '1_1_town': { name: '狮眼守望', type: 'town' },
  '1_2_town': { name: '森林营地', type: 'town' },
  '1_3_town': { name: '萨恩营地', type: 'town' },
  '1_4_town': { name: '统治者之殿', type: 'town' },
  '1_5_town': { name: '狱卒之塔', type: 'town' },
  KalguuranSettlersLeague: { name: '君锋镇', type: 'town' },
  HeistHub: { name: '黄金港', type: 'town' },
  HideoutForest: { name: '苍翠藏身处', type: 'hideout' },
  HideoutForest_Claim: { name: '苍翠藏身处', type: 'hideout' },
  HeistHubEndless: { name: '黄金湾', type: 'town' },
  HeistHubSolo: { name: '黄金港', type: 'town' },
  DelveHub: { name: '矿坑营地', type: 'town' },
  Menagerie: { name: '兽园', type: 'town' },
  SanctumFoyer: { name: '禁忌圣域', type: 'side-area' },
  HallsOfTheDead: { name: '亡者之厅', type: 'town' },
  LabyrinthAirlock: { name: '志士之试炼', type: 'town' },
  '2_6_town': { name: '狮眼守望', type: 'town' },
  '2_7_town': { name: '桥头营地', type: 'town' },
  '2_8_town': { name: '萨恩营地', type: 'town' },
  '2_9_town': { name: '统治者之殿', type: 'town' },
  '2_10_town': { name: '奥瑞亚码头', type: 'town' },
  MavenHub: { name: '贤主之邀', type: 'boss' },
  Hideout: { name: '藏身处', type: 'hideout' },
  LioneyeWatch: { name: '狮眼守望', type: 'town' },
  AbyssLeague: { name: '深渊', type: 'side-area' },
  VaalSideArea: { name: '瓦尔附属区域', type: 'side-area' },
  LabyrinthTrial: { name: '升华试炼', type: 'side-area' }
})

// 简体中文名称参考：https://poedb.tw/cn/Hideout
const HIDEOUT_NAMES = Object.freeze({
  Lush: '苍翠藏身处', Trench: '劫匪的沟渠藏身处', Battlescarred: '战痕藏身处',
  Coastal: '海岸藏身处', Enlightened: '启迪藏身处', Overgrown: '密草藏身处',
  Immaculate: '洁净藏身处', Unearthed: '墓穴藏身处', Backstreet: '暗巷藏身处',
  Undercity: '地下城藏身处', Excavated: '考古藏身处', Stately: '宏伟藏身处',
  Coral: '珊瑚藏身处', Baleful: '罪孽藏身处', Desert: '荒漠藏身处',
  Skeletal: '钢骨藏身处', Luxurious: '奢华藏身处', Cartography: '制图师藏身处',
  Towering: '塔楼藏身处', Corrupted: '腐化藏身处', Innocent: '纯净藏身处',
  Shaper: '塑界藏身处', Furious: '狂怒藏身处', Champions: '勇士藏身处',
  Indomitable: '不屈藏身处', Morbid: '灾病藏身处', Eclipsed: '日蚀藏身处',
  Ravenous: '贪婪藏身处', SunkenCity: '沉陷藏身处', ShapersRealm: '众星藏身处',
  TwilightTemple: '分割藏身处', HighGardens: '树栖藏身处', Haunted: '鬼语藏身处',
  PrisonTower: '野蛮藏身处', CrimsonTemple: '血色藏身处', Iceberg: '冰川藏身处',
  Mountain: '实验藏身处', Void: '虚空藏身处'
})

// 来源：https://poedb.tw/cn/Atlas_of_Worlds（2026-09-08）
const MAP_NAMES = Object.freeze({
  "Beach": "危岩海滩",
  "Strand": "致命岩滩",
  "Dunes": "暮色沙丘",
  "Desert": "贫瘠之地",
  "DesertSpring": "荒漠绿洲",
  "JungleValley": "剧毒林谷",
  "TropicalIsland": "晴空幽岛",
  "Atoll": "滨海山丘",
  "Island": "海岛",
  "Mesa": "赤红山地",
  "Canyon": "峡谷",
  "CitySquare": "城中广场",
  "CrimsonTemple": "玫红神殿",
  "DefiledCathedral": "污染教堂",
  "BurialChambers": "幽闭墓领",
  "UndergroundSea": "滨海幽穴",
  "UndergroundRiver": "地底之河",
  "DriedLake": "干涸湖岸",
  "Plateau": "海风高原",
  "Glacier": "冰川",
  "FrozenCabins": "冻结之舱",
  "City": "城市",
  "Park": "寂夜林苑",
  "Gardens": "花园迷宫",
  "Palace": "神域之殿",
  "Tower": "高塔",
  "Courtyard": "奇迹之墙",
  "Promenade": "月色回廊",
  "Colonnade": "激战柱廊",
  "Arcade": "崩坏长廊",
  "Arsenal": "古兵工厂",
  "Armoury": "武器库",
  "Dungeon": "地牢",
  "Cells": "幽魂监牢",
  "Crypt": "墓穴",
  "Catacombs": "地下墓穴",
  "Graveyard": "堕影墓场",
  "SpiderForest": "蜘蛛森林",
  "SpiderLair": "巨蛛巢穴",
  "ArachnidNest": "异蛛巢穴",
  "ArachnidTomb": "灵虫墓穴",
  "AshenWood": "灰烬森林",
  "Woods": "森林",
  "Orchard": "密林果园",
  "Terrace": "海滨台地",
  "Villa": "别墅",
  "Residence": "神主居所",
  "Lighthouse": "灯塔",
  "Shore": "海岸",
  "Pier": "怒浪之港",
  "Port": "中转码头",
  "Shipyard": "炽炎船坞",
  "Wharf": "货运码头",
  "Reef": "危机海礁",
  "Grotto": "幽暗地穴",
  "Waterways": "危机水道",
  "WastePool": "废水池",
  "Sewer": "下水道",
  "Marshes": "绝望沼泽",
  "Estuary": "赤寒河岸",
  "Silo": "圆形秘窖",
  "Factory": "工厂遗迹",
  "Foundry": "锻晶车间",
  "Laboratory": "实验密室",
  "LavaLake": "熔岩之湖",
  "Volcano": "火山",
  "Caldera": "寂灵之渊",
  "Summit": "寒顶之巅",
  "Coves": "海湾",
  "VaalPyramid": "瓦尔金字塔",
  "VaalTemple": "瓦尔密殿",
  "Cemetery": "晨曦墓地",
  "Museum": "古博物馆",
  "Bog": "沼泽",
  "GraveTrough": "荒坟凹地",
  "Mausoleum": "王陵",
  "IvoryTemple": "白玉神庙",
  "Excavation": "挖掘场",
  "Springs": "孢子空谷",
  "TortureChamber": "远古街区",
  "CoralRuins": "珊瑚遗迹",
  "Iceberg": "极寒冰原",
  "Cage": "恶念牢笼",
  "Bazaar": "远古市集",
  "InfestedValley": "疫源林谷",
  "Belfry": "钟楼",
  "Courthouse": "失序教院",
  "Temple": "夺魂之殿",
  "RelicChambers": "古藏密室",
  "Channel": "秘密通道",
  "AridLake": "荒芜湖域",
  "Conservatory": "古塔内堂",
  "Ghetto": "赤贫居所",
  "HauntedMansion": "幽魂宅邸",
  "DarkForest": "夜语幽林",
  "Lookout": "危墙之地",
  "Geode": "水晶洞穴",
  "PrimordialPool": "起源之池",
  "SulphurVents": "硫磺蚀岸",
  "ColdRiver_": "寒霜之河",
  "ToxicSewer": "剧毒水道",
  "Colosseum": "大决斗场",
  "ForkingRiver": "分叉之河",
  "CrystalOre": "冰冷通道",
  "Core": "核心",
  "OvergrownShrine": "密草神殿",
  "Vault": "机关宝库",
  "Ramparts": "奇迹之墙",
  "FloodedMine": "积水矿坑",
  "BrambleValley": "黑棘谷地",
  "ForbiddenWoods": "禁断之林",
  "Alleyways": "危城巷弄",
  "Tribunal": "陨坑",
  "Lair": "巢穴",
  "Siege": "围城",
  "Stagnation": "停滞区",
  "Fields": "无边原野",
  "SunkenCity": "沉沦之城",
  "Malformation": "畸形亡域",
  "Basilica": "神圣大教堂",
  "Plaza": "广场",
  "Pit": "巨坑",
  "MineralPools": "废弃矿山",
  "Chateau": "古堡",
  "Phantasmagoria": "魔灵幻狱",
  "Chimera": "奇美拉领域",
  "Hydra": "九头蛇巢穴",
  "Minotaur": "牛头人迷宫",
  "Phoenix": "不死鸟锻台",
  "Sanctuary": "没落圣所",
  "Citadel": "幽闭城塞",
  "Fortress": "上古堡垒",
  "Abomination": "憎恨之地",
  "Ziggurat": "灵祭塔庙",
  "StrandUnique": "禁闭祭坛",
  "AtollUnique": "混沌之渊",
  "CemeteryUnique": "魔诅之域",
  "DunesUnique": "阿尔伦神柱",
  "BoneCryptUnique": "远古之印",
  "UndergroundRiverUnique": "塞尔.布雷德狼穴",
  "VaalPyramidUnique": "阿兹里的秘宝库",
  "CourtyardUnique": "维克塔广场",
  "ShoreUnique": "贼窝",
  "MoonTempleUnique": "暮光古庙",
  "TempleUnique": "沉沦之间",
  "MuseumUnique": "幽秘博物馆",
  "CursedCryptUnique": "懦者的试验",
  "PromenadeUnique": "元帅殿堂",
  "OvergrownShrineUnique": "轮回的梦魇",
  "TortureChamberUnique": "欧霸的咒怨宝库",
  "NecropolisUnique": "亡者之财"
})

const LEGACY_MAP_NAMES = Object.freeze({
  "沙滩": "危岩海滩",
  "荒漠": "贫瘠之地",
  "丛林山谷": "剧毒林谷",
  "热带岛屿": "晴空幽岛",
  "环礁": "滨海山丘",
  "平顶荒漠": "赤红山地",
  "危城广场": "城中广场",
  "高原": "海风高原",
  "冰封小屋": "冻结之舱",
  "园林": "寂夜林苑",
  "花园": "花园迷宫",
  "长廊": "月色回廊",
  "柱廊": "激战柱廊",
  "拱廊": "崩坏长廊",
  "军械库": "古兵工厂",
  "禁魂炎狱": "幽魂监牢",
  "墓园": "堕影墓场",
  "蜘蛛巢穴": "巨蛛巢穴",
  "蛛网巢穴": "异蛛巢穴",
  "蛛网墓穴": "灵虫墓穴",
  "果园": "密林果园",
  "露台": "海滨台地",
  "宅邸": "神主居所",
  "码头": "怒浪之港",
  "港口": "中转码头",
  "造船厂": "炽炎船坞",
  "岩洞": "幽暗地穴",
  "水道": "危机水道",
  "湿地": "绝望沼泽",
  "河口": "赤寒河岸",
  "筒仓": "圆形秘窖",
  "工厂": "工厂遗迹",
  "铸造厂": "锻晶车间",
  "实验室": "实验密室",
  "熔岩湖": "熔岩之湖",
  "火山口": "寂灵之渊",
  "山顶": "寒顶之巅",
  "瓦尔神殿": "瓦尔密殿",
  "博物馆": "古博物馆",
  "墓穴地沟": "荒坟凹地"
})

function readableAreaId(areaId) {
  return String(areaId || '')
    .replace(/^(?:MapWorlds|Map|Area)/, '')
    .replace(/([a-z\d])([A-Z])/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .trim() || '未知区域'
}

export function classifyArea(areaId) {
  const id = String(areaId || '').trim().replace(/^([12]) (\d+) (.+)$/, (_, part, act, rest) => `${part}_${act}_${rest.replace(/ /g, '_')}`)
  const compactId = id.replace(/\s+/g, '')
  const known = AREAS[id] || AREAS[compactId]
  if (known) return { version: AREA_CATALOG_VERSION, areaId: id, areaName: known.name, type: known.type, supported: true }
  if (/Hideout/i.test(compactId)) {
    const name = HIDEOUT_NAMES[compactId.replace(/Hideout/ig, '')]
    if (name) return { version: AREA_CATALOG_VERSION, areaId: id, areaName: name, type: 'hideout', supported: true }
  }
  const mapName = MAP_NAMES[id.replace(/^MapWorlds/, '')]
  if (mapName) return { version: AREA_CATALOG_VERSION, areaId: id, areaName: mapName, type: 'map', supported: true }
  const type = /^MapWorlds/i.test(id) ? 'map'
    : /(?:Hideout)/i.test(id) ? 'hideout'
      : /(?:Town|Lioneye|Encampment|Oriath|KaruiShores)/i.test(id) ? 'town'
        : /(?:Abyss|VaalSide|LabyrinthTrial)/i.test(id) ? 'side-area' : 'unknown'
  const areaName = type === 'hideout' ? '藏身处' : type === 'town' ? '城镇' : readableAreaId(id)
  return { version: AREA_CATALOG_VERSION, areaId: id, areaName, type, supported: type !== 'unknown' }
}

export { AREA_CATALOG_VERSION }

export function normalizeMapName(areaId, value) {
  const name = String(value || '').trim()
  const id = String(areaId || '').trim()
  const known = /^MapWorlds/.test(id) ? MAP_NAMES[id.slice(9)] : null
  return known || LEGACY_MAP_NAMES[name] || name
}
